hw7 is completed
Dasha-Belozerceva/DariaBelozertseva pull request #7
Opened 2020-04-23 23:13 UTC by Dasha-Belozerceva

2020-04-25 07:02 UTC, troe88 requested changes

2020-04-25 07:02 UTC, troe88 commented on src/main/java/hw7/pages/MetalsAndColorsPage.java
> +        metalsAndColorsForm.fillMetalsAndColorsForm(metalsAndColorsData);
Why don't you create "submit"-kind method instead of "fill" and "clickSubmitButton" ?

2020-04-25 07:02 UTC, troe88 commented on src/main/java/hw7/utils/PropertiesDataInitialize.java
> +        } catch (
Code convention.

2020-04-25 07:02 UTC, troe88 commented on src/main/java/hw7/utils/PropertiesDataInitialize.java
> +        } catch (
Is that really necessary create two catch blocks here ?

2020-04-25 07:02 UTC, troe88 commented on src/test/java/hw7/JdiSiteTests.java
> +        assertTrue(JdiSite.metalsAndColorsPage.isActualResultTheSameWithExpected(metalsAndColorsData));
What are you gonna get as exception message in case of failure ?

2020-04-25 07:02 UTC, troe88 commented on src/test/java/hw7/JdiSiteTests.java
> +public class JdiSiteTests extends BaseClass{
Code convention

2020-04-25 07:02 UTC, troe88 commented on src/main/java/hw7/pages/MetalsAndColorsPage.java
> +        boolean isTheSame = true;
What is the reason of this variable here ?

2020-04-25 13:49 UTC, Dasha-Belozerceva commented on src/test/java/hw7/JdiSiteTests.java
> +public class JdiSiteTests extends BaseClass{
changed imports to import static org.testng.Assert.*;

2020-04-25 13:50 UTC, Dasha-Belozerceva commented on src/main/java/hw7/utils/PropertiesDataInitialize.java
> +        } catch (
done (put expression inside brackets in right place)

2020-04-25 13:52 UTC, Dasha-Belozerceva commented on src/main/java/hw7/utils/PropertiesDataInitialize.java
> +        } catch (
FileNotFoundException extends IOException, so I should delete catch block of  FileNotFoundException here
Done.

2020-04-25 14:13 UTC, Dasha-Belozerceva commented on src/main/java/hw7/pages/MetalsAndColorsPage.java
> +        metalsAndColorsForm.fillMetalsAndColorsForm(metalsAndColorsData);
done.

2020-04-27 06:26 UTC, troe88 requested changes

2020-04-27 06:26 UTC, troe88 commented on src/test/java/hw7/JdiSiteTests.java
> +public class JdiSiteTests extends BaseClass{
Take a look at 'BaseClass{'

2020-04-27 06:26 UTC, troe88 commented on src/test/java/hw7/JdiSiteTests.java
> +        assertTrue(JdiSite.metalsAndColorsPage.isActualResultTheSameWithExpected(metalsAndColorsData));
So, if the test failed, we will only see "expect true but false" in our log. Is that enough to realise the root cause of failure ?

2020-04-27 06:26 UTC, troe88 commented on src/main/java/hw7/pages/MetalsAndColorsPage.java
> +        boolean isTheSame = true;
x2

2020-04-27 09:33 UTC, Dasha-Belozerceva commented on src/test/java/hw7/JdiSiteTests.java
> +public class JdiSiteTests extends BaseClass{
done

2020-04-27 09:39 UTC, troe88 approved these changes

2020-04-27 10:35 UTC, merged